apiVersion: v1
kind: Service
metadata:
  labels:
    cattle.io/creator: norman
  name: user-service
  namespace: staging
spec:
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    workload.user.cattle.io/workloadselector: deployment-staging-user-service
  sessionAffinity: None
  type: ClusterIP